name: app_firebase
description: "Firebase integration services for Runtime Config, Performance, and App Check."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  firebase_app_check: ^0.4.1+2
  firebase_core: ^4.4.0
  firebase_performance: ^0.11.0+9
  firebase_remote_config: ^6.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
