// Mocks generated by Mockito 5.4.6 from annotations
// in app_analytics/test/middleware/consent_middleware_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_analytics/src/storage/consent_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConsentStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockConsentStorage extends _i1.Mock implements _i2.ConsentStorage {
  MockConsentStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> hasConsent() =>
      (super.noSuchMethod(
            Invocation.method(#hasConsent, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setConsent(bool? granted) =>
      (super.noSuchMethod(
            Invocation.method(#setConsent, [granted]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearConsent() =>
      (super.noSuchMethod(
            Invocation.method(#clearConsent, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
